spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
     ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        show_sql: true
    profiles: local
    devtools:
      restart:
        enabled: true
        additional-paths: classpath:/
      livereload:
        enabled: false
    thymeleaf:
      cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug